### ISSUE TITLE
Add recipe support

### ISSUE THREAD

**Issue by lawremi** [AppliedEnergistics/AE2-RotaryCraft-API#2]
Your build of the RotaryCraft API (and distributing it via maven) has been very helpful, and now we would like to make use of it for adding recipes to RotaryCraft machines. All we need is the `RecipeInterface` class. Would this be amenable? Thanks!

**Comment by yueh** [comment]
Honestly you should request it from the actual mod developer.
This here is just a workaround for us. But we do not intend to actually maintain it besides the absolute minimum requirements for AE. Clearly not our job as 3rd party.

If for whatever reason they are not willing to provide a usable api artifact and potentially a public maven repo, it is probably a good idea to reconsider your support for it.
